
# 在主题配置文件中： themes/next/_config.yml
reward:
  enable: true
  comment: “谢谢支持~”
  platforms:
    - alipay
    - wechat
  alipay: /source/images/Alipay.jpg  # 上传你的收款码图片路径
  wechat: /source/images/Wechatpay.png